### ISSUE TITLE
"Normalize" colors to return RGB?

### ISSUE THREAD

**Issue by m-mohr** [weatherlayers/cpt2js#1]
As a consumer, I think it would be nice to have an option that allows getting the colors always as RGB so that I don't need to care about the different types (color name, RGB, HSV, HSL)?

Thanks for this library!

**Comment by zakjan** [comment]
Yes, I focused on the palette file parsing first, so I offloaded color handling to another library [Chroma.js](https://github.com/gka/chroma.js) for now. I chose it because it's used by [georaster-layer-for-leaflet](https://github.com/GeoTIFF/georaster-layer-for-leaflet) as well.

There is an issue that transforming colors to RGB is not enough, because the palette color mode also affects how interpolated colors are computed.

Rainbow palette in HSV:

```
# COLOR_MODEL = hsv
0	300-1-1	0.5	150-1-1
0.5	150-1-1	1	0-1-1
```

<img width="563" alt="Screenshot 2022-05-04 at 16 17 08" src="https://user-images.githubusercontent.com/173585/166701101-7279b474-c069-45d5-805a-79fe73ec9bcf.png">

and transformed to RGB at the same values:

```
0	255/0/255	0.5	0/255/128
0.5	0/255/128	1	255/0/0
```

<img width="564" alt="Screenshot 2022-05-04 at 16 16 34" src="https://user-images.githubusercontent.com/173585/166701132-6ecdb23d-3bc1-4bc2-a529-cfec4a7bef77.png">

I'm going to investigate improving the output form the current JSON object to a function `(value: number) => Color`, similar to [Chroma.js scale](https://vis4.net/chromajs/#chroma-scale).

**Comment by zakjan** [comment]
So, your suggestion made me so much sense, that I refactored the library using a custom lightweight Chroma.js bundle to return a function. Also I renamed it to just `cpt2js`, because no longer returns a JSON.

But I screwed up releasing, and now I have to wait one day so that npm allows me to do it properly again. 😫 At least the demo works.

**Comment by zakjan** [comment]
Released

**Comment by m-mohr** [comment]
Thank you!
